### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by Oliver-CISC** [AntonyCorbett/HelixBackupFiles#5]
Is this application still supported? I am having problems running on Windows 10 using a backup file from Helix 3.7 OS.

**Comment by AntonyCorbett** [comment]
@Oliver-CISC It was last tested on firmware 2.81, so it may be that the backup file format has changed. But what problems are you having, please?

**Comment by Oliver-CISC** [comment]
Hi @AntonyCorbett thanks for responding so quickly.

I'm attempting to follow your instructions to unpack the presets in a single .hxb backup file. I have downloaded and unzipped HelixBackupFileConsole 1.0.0.1 and placed my backup file into the same folder on my desktop. I then cd into the folder and run
`HelixBackupFileConsole.exe Helix Rack Backup 2022-Jun-26.hxb`

This produces the error shown below:
![image](https://github.com/AntonyCorbett/HelixBackupFiles/assets/89128947/c0004374-7ae5-46a5-b884-0c583368534f)

Perhaps I have mistakenly got the process wrong? Thanks for any guidance!

**Comment by AntonyCorbett** [comment]
@Oliver-CISC The problem is likely that the runtime is not installed on your system. I have made a new release with the runtime embedded, If you're using Windows, you probably want to use the HelixBackupFileConsole.exe file (the first download). See the instructions in the README (which you were correctly following).

**Comment by Oli-Thompson** [comment]
@AntonyCorbett Thanks, that worked perfectly! Appreciate you developing this utility, and for the quick support!
